[project]
name = "happy-day"
version = "0.1.0"
description = "Сервис по поздравлению коллег с праздниками"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.6",
    "pillow>=11.3.0",
    "pytelegrambotapi>=4.29.1",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
]
