# Generated by Django 5.2.6 on 2025-09-17 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model_id', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employees', models.ManyToManyField(related_name='ai_messages', to='staff.employee')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openrouter.aimodel')),
            ],
        ),
        migrations.AddField(
            model_name='aimodel',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openrouter.token'),
        ),
        migrations.AlterUniqueTogether(
            name='aimodel',
            unique_together={('model_id', 'token')},
        ),
    ]
