# Generated by Django 5.2.6 on 2025-09-19 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('value', models.CharField(max_length=255, unique=True, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Ключ API',
                'verbose_name_plural': 'Ключи API',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='LLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('is_free', models.BooleanField(default=False, verbose_name='Токены не монетизируются')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openrouter.provider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('prompt', models.TextField(verbose_name='Промпт')),
                ('is_default', models.BooleanField(default=False, verbose_name='Используется по-умолчанию')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openrouter.apikey', verbose_name='Ключ API')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openrouter.llmodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openrouter.service', verbose_name='Сервис')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
