# Generated by Django 5.2.6 on 2025-09-19 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('chat_id', models.CharField(max_length=255, verbose_name='Идентификатор чата')),
            ],
            options={
                'verbose_name': 'Чаты',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('is_default', models.BooleanField(default=False, verbose_name='Используется по-умолчанию')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.bot', verbose_name='Бот')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.chat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Отправитель',
                'verbose_name_plural': 'Отправители',
                'unique_together': {('chat', 'bot')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.publisher', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
